apiVersion: v1
kind: ConfigMap
metadata:
  name: forum-app-config
data:
  spring.profiles.active: "prod"
  spring.datasource.url: "jdbc:mysql://mysql-service:3306/forumdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  spring.jpa.hibernate.ddl-auto: "update"
  spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL8Dialect"
  spring.jpa.show-sql: "false"
  spring.jpa.open-in-view: "false"
  logging.level.org.springframework: "INFO"
  logging.level.com.example.forum: "INFO"
  server.port: "8080"

