apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-app
  labels:
    app: forum-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forum-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: forum-app
    spec:
      containers:
      - name: forum-app
        image: ${DOCKER_REGISTRY}/forum-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: forum-app-config
              key: spring.profiles.active
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: forum-app-config
              key: spring.datasource.url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: forum-app-secrets
              key: spring.datasource.username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: forum-app-secrets
              key: spring.datasource.password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: forum-app-config
              key: spring.jpa.hibernate.ddl-auto
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
      restartPolicy: Always

