apiVersion: v1
kind: Secret
metadata:
  name: forum-app-secrets
type: Opaque
data:
  # These are base64 encoded placeholders
  # In production, replace these with actual encoded values
  # Example: echo -n "forumuser" | base64
  spring.datasource.username: Zm9ydW11c2Vy  # base64 encoded "forumuser"
  spring.datasource.password: Zm9ydW1wYXNz  # base64 encoded "forumpass"
  
  # Optional: Add JWT secret if your app uses it
  # jwt.secret: c2VjcmV0LWtleS1mb3Itand0LXRva2Vu

