apiVersion: v1
kind: Service
metadata:
  name: forum-app
  labels:
    app: forum-app
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: forum-app
---
# Uncomment this section if you need a NodePort service
# apiVersion: v1
# kind: Service
# metadata:
#   name: forum-app-nodeport
#   labels:
#     app: forum-app
# spec:
#   type: NodePort
#   ports:
#   - port: 8080
#     targetPort: 8080
#     nodePort: 30080
#     protocol: TCP
#     name: http
#   selector:
#     app: forum-app

